// <auto-generated />
using System;
using AlMaximo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlMaximo.Migrations
{
    [DbContext(typeof(AlMaximoDbContext))]
    partial class AlMaximoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlMaximo.Core.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Apellido2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumNomina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NumNomina")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("AlMaximo.Core.Entities.EmpleadoAutorizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("EmpleadosAutorizadores");
                });

            modelBuilder.Entity("AlMaximo.Core.Entities.Prestamo", b =>
                {
                    b.Property<int>("IdPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrestamo"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("AutorPersonaQueAutorizaId")
                        .HasColumnType("int");

                    b.Property<decimal>("CantidadTotalAPagar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CantidadTotalPrestada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaFinalPago")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaPrimerPago")
                        .HasColumnType("date");

                    b.Property<decimal>("InteresAprobado")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("InteresMoratorio")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoPagoAbonoId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAbonadoCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAbonadoIntereses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPrestamo");

                    b.HasIndex("AutorPersonaQueAutorizaId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("TipoPagoAbonoId");

                    b.ToTable("Prestamos", t =>
                        {
                            t.HasCheckConstraint("CK_Prestamos_CantidadPositiva", "[CantidadTotalPrestada] > 0");

                            t.HasCheckConstraint("CK_Prestamos_InteresMoratorioPositivo", "[InteresMoratorio] >= 0");

                            t.HasCheckConstraint("CK_Prestamos_InteresPositivo", "[InteresAprobado] >= 0");
                        });
                });

            modelBuilder.Entity("AlMaximo.Core.Entities.PrestamoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("AutorPersonaQueAutorizaId")
                        .HasColumnType("int");

                    b.Property<decimal>("CantidadTotalAPagar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CantidadTotalPrestada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFinalPago")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaOperacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaPrimerPago")
                        .HasColumnType("date");

                    b.Property<decimal>("InteresAprobado")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("InteresMoratorio")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoPagoAbonoId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAbonadoCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAbonadoIntereses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuarioOperacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AutorPersonaQueAutorizaId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PrestamoId");

                    b.HasIndex("TipoPagoAbonoId");

                    b.ToTable("PrestamosHistorial");
                });

            modelBuilder.Entity("AlMaximo.Core.Entities.TipoPagoAbono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NombreCorto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NombreCorto")
                        .IsUnique();

                    b.ToTable("TipoPagosAbonos");
                });

            modelBuilder.Entity("AlMaximo.Core.Entities.EmpleadoAutorizador", b =>
                {
                    b.HasOne("AlMaximo.Core.Entities.Empleado", "Empleado")
                        .WithMany("EmpleadoAutorizadores")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AlMaximo.Core.Entities.Prestamo", b =>
                {
                    b.HasOne("AlMaximo.Core.Entities.EmpleadoAutorizador", "AutorPersonaQueAutoriza")
                        .WithMany("PrestamosAutorizados")
                        .HasForeignKey("AutorPersonaQueAutorizaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlMaximo.Core.Entities.Empleado", "Empleado")
                        .WithMany("Prestamos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlMaximo.Core.Entities.TipoPagoAbono", "TipoPagoAbono")
                        .WithMany("Prestamos")
                        .HasForeignKey("TipoPagoAbonoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AutorPersonaQueAutoriza");

                    b.Navigation("Empleado");

                    b.Navigation("TipoPagoAbono");
                });

            modelBuilder.Entity("AlMaximo.Core.Entities.PrestamoHistorial", b =>
                {
                    b.HasOne("AlMaximo.Core.Entities.EmpleadoAutorizador", "AutorPersonaQueAutoriza")
                        .WithMany()
                        .HasForeignKey("AutorPersonaQueAutorizaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlMaximo.Core.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlMaximo.Core.Entities.Prestamo", "Prestamo")
                        .WithMany("HistorialCambios")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlMaximo.Core.Entities.TipoPagoAbono", "TipoPagoAbono")
                        .WithMany()
                        .HasForeignKey("TipoPagoAbonoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AutorPersonaQueAutoriza");

                    b.Navigation("Empleado");

                    b.Navigation("Prestamo");

                    b.Navigation("TipoPagoAbono");
                });

            modelBuilder.Entity("AlMaximo.Core.Entities.Empleado", b =>
                {
                    b.Navigation("EmpleadoAutorizadores");

                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("AlMaximo.Core.Entities.EmpleadoAutorizador", b =>
                {
                    b.Navigation("PrestamosAutorizados");
                });

            modelBuilder.Entity("AlMaximo.Core.Entities.Prestamo", b =>
                {
                    b.Navigation("HistorialCambios");
                });

            modelBuilder.Entity("AlMaximo.Core.Entities.TipoPagoAbono", b =>
                {
                    b.Navigation("Prestamos");
                });
#pragma warning restore 612, 618
        }
    }
}
